config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/demo', to: "guests#show", as: "demo"

  resource :dashboard, only: [:show]

  get '/w/new', to: 'workspaces#new', as: :new_workspace
  get '/w/:wid(/:name)', to: 'workspaces#show', constraints: { wid: /[^\/]+/}, as: :workspace

  api version: 1, module: "api/v1" do
    resources :workspaces, :only => [:create, :index]

    scope '/w/:wid', constraints: { wid: /[^\/]+/} do
      resource :workspace, only: [:show], path: ""
      resources :availabilities, :only => [:show]
      resources :resources, :only => [:create]
      resources :resource_groups, :only => [:create]
      resources :allocations, :only => [:create, :index, :destroy] do
        collection do
          post '/:allocation_id', to: "allocations#update", as: :update
        end
      end
    end
  end

  root to: "pages#index"

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/models/workspace.rb
class Workspace < ActiveRecord::Base
  include Colorizable

  DEFAULT_RESOURCES_NAME = "resource".freeze
  DEFAULT_RESOURCE_GROUPS_NAME = "group".freeze

  validates :name, presence: true
  validates :user_id, presence: true

  has_many :resource_groups, foreign_key: :workspace_id, inverse_of: :workspace
  has_many :resources, foreign_key: :workspace_id, inverse_of: :workspace
  has_many :allocations, inverse_of: :workspace
  belongs_to :user, inverse_of: :workspaces

  before_validation :with_defaults, on: :create

  scope :from_unique_id, -> (uid) { where(id: $hashids.decode(uid).first) }

  # this method returns a unique id for the workspace. This is so we can have unique urls
  def unique_id
    $hashids.encode(self.id)
  end

  def with_defaults
    init_resource_name_and_group_name
    init_name_generator
    self
  end

  def resource_groups_name
    metadata["resource_groups_name"].capitalize
  end

  def resources_name
    metadata["resources_name"].capitalize
  end

  private
  # this method sets the default resource name and resource group name for a worskpace.
  # remember the user is able to change this later
  def init_resource_name_and_group_name
    metadata["resources_name"]        ||= DEFAULT_RESOURCES_NAME
    metadata["resource_groups_name"]  ||= DEFAULT_RESOURCE_GROUPS_NAME
  end

  # setups the name of the workspace if the user did not pass any
  def init_name_generator
    unless self.name.present?
      self.name = Bazaar.super_object
    end
  end
end

app/controllers/api/v1/workspaces_controller.rb
class Api::V1::WorkspacesController < ApiController
  include ManageDefaultDates
  before_action :init_dates_range
  skip_before_filter :authenticate_user!, only: [:show]

  version 1

  def index
    expose current_user.workspaces.page(params[:page]).per(params[:per]), each_serializer: WorkspaceSerializer
  end

  def create
    workspace = current_user.workspaces.create(workspace_params)
    expose workspace, serializer: WorkspaceSerializer, metadata:{ server_message: "Workspace created!"}
  end

  def show
    workspace = Workspace.from_unique_id(workspace_id).includes(:resources, :resource_groups).first!
    serialized = WorkspaceSerializer.new(workspace).serializable_hash
    serialized[:allocations] = ActiveModel::ArraySerializer.new(workspace.allocations.overlapping(@start_date, @end_date), each_serializer: AllocationSerializer).serializable_array
    expose serialized, metadata: calculate_statistics(serialized)
  end

  private
    def calculate_statistics(workspace)
      allocated_resources = workspace[:allocations].map{|r| r[:resource_id]}.uniq.count
      allocated_groups = workspace[:allocations].map{|r| r[:resource_group_id]}.uniq

      groups_without_allocations = (workspace[:resource_groups].map{|r| r[:id]} - allocated_groups).count

      total_resources = workspace[:resources].count
      {
        estatistics: {
          percentage_of_resources_allocated: total_resources > 0 ? (allocated_resources*100)/total_resources : 0,
          allocated_resources: allocated_resources,
          total_resources: total_resources,
          groups_without_allocations: groups_without_allocations
        }
      }
    end

    def workspace_params
      params.require(:workspace).permit(:name, metadata: [:resources_name, :resource_groups_name])
    end

    def workspace_id
      params.require(:wid)
    end
end

app/controllers/api/workspace_controller.rb
class Api::V1::WorkspaceController < ApiController
  version 1

  def index
    expose current_user.workspaces, each_serializer: WorkspaceSerializer
  end

  def create
    workspace = current_user.workspaces.create(workspace_params)
    expose workspace, serializer: WorkspaceSerializer
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :load_workspace, only: [:show]

  def show
  end

  def new
    @workspace = Workspace.new.with_defaults
  end

  private
    def load_workspace
      @workspace = Workspace.from_unique_id(params[:wid]).first!
    end
end

app/views/workspaces/new.html.erb
<%= form_for @workspace, url: workspaces_path(version: 1), remote: true do |f| %>
  Name: <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/workspaces/show.html.erb
<div class="workspace">
  <div class="workspace__chart">
    <div class="js-workspace-chart"></div>
  </div>

  <% if user_signed_in? && @workspace.user == current_user %>
    <div class="resources-container">
      <button class="orb orb--resources workspace__orb--left js-toggle-sidebar" data-target=".js-resources-sidebar">
        <span class="workspace-orb__label">
          <i class="icon icon--pawn"></i>
        </span>
        <span class="workspace-orb__label--alt">Close</span>
      </button>

      <section class="resources sidebar workspace__sidebar--left js-resources-sidebar">
        <h1 class="resources__title">Resources</h1>
        <ul class="list--stack resources__list js-resources-list">
          <%- @workspace.resources.each do |resource| %>
            <li> <span> <%= resource.name %> 
              <a href="javascript:;" class="js-open-allocate-form button button--small button--success float--right" data-resource-name="<%= resource.name %>" data-resource-id="<%= resource.id %>">Allocate</a></span> </li>
          <%- end %>
        </ul>

        <form class="js-new-resource-form" action="<%= resources_path(version:1, wid: @workspace.unique_id)%>" data-method="post" >
          <div class="form-inline">
            <input type="text" autocomplete="off" class="form-control form-control--clear input--large js-group-input-name js-name" placeholder="<%= @workspace.resources_name %> Name" name="resource[name]" data-name="name">
            <input type="submit" class="button button--info button--large float--right js-submit" value="Add">
          </div>
        </form>

      </section>
    </div>

    <div class="groups-container">
      <button class="orb orb--groups workspace__orb--right js-toggle-sidebar" data-target=".js-groups-sidebar">
        <span class="workspace-orb__label">
          <i class="icon icon--group"></i>
        </span>
        <span class="workspace-orb__label--alt">Close</span>
      </button>

      <div class="groups sidebar workspace__sidebar--right js-groups-sidebar">
        <form class="js-new-resource-group-form" action="<%= resource_groups_path(version:1, wid: @workspace.unique_id)%>" data-method="post" >
          <div class="form-inline">
            <input type="text" autocomplete="off" class="form-control form-control--clear input--large js-group-input-name js-name" placeholder="<%= @workspace.resource_groups_name %> Name" name="resource_group[name]" data-name="name">
            <input type="submit" class="button button--info button--large float--right js-submit" value="OK">
          </div>
        </form>
      </div>
    </div>
  <% end %>

  <div class="workspace__slider">
    <input type="text" id="js-workspace-date-slider" />
  </div>
</div>

<% content_for :javascripts do %>
  <script id="js-availability-list-template" type="text/html">
    <h3 class="zeta">Select from current availability:</h2>
    <ul class="list--stack">
      {{#response}}
        <li>
          <strong>From: </strong> {{human_start_date}} - <strong>To: </strong> {{human_end_date}}
          <a href="javascript:;" class="js-availability-use-this button button--small button--success float--right" data-start-date="{{start_date}}" data-end-date="{{end_date}}">Use this range</a>
        </li>
      {{/response}}
    </ul>
  </script>

  <script id="js-allocation-form-template" type="text/html">
    <h1 class="delta text--center">{{resourceName}} Allocation</h3>
    <form class="js-allocation-form clearfix" action="<%= allocations_path(version:1, wid: @workspace.unique_id)%>/{{allocationId}}" data-method="post" >
      <input class="js-resource-id" type="hidden" name="allocation[resource_id]" data-name="resource_id" value="{{resourceId}}">

      <div class="form push--bottom">
        <label for="allocation[resource_group_id]" class="label"><%= @workspace.resource_groups_name %></label>

        <select class="form-control js-resource-group-id" name="allocation[resource_group_id]" data-name="resource_group_id">
          {{#resourceGroups}}
            <option value="{{id}}">{{name}}</option>
          {{/resourceGroups}}
        </select>
      </div>

      <div class="form-inline push--bottom">
        <label for="allocation[start_date]" class="label">From</label>
        <input class="js-start-date form-control" type="text" name="allocation[start_date]" data-name="start_date" value="{{startDate}}">
        <label for="allocation[end_date]" class="label">To</label>
        <input class="js-end-date form-control" type="text" name="allocation[ent_date]" data-name="end_date" value="{{endDate}}">
      </div>

      <a href="javascript:;" class="js-delete-allocation-link text--danger text--small link--cancel" data-url="<%= allocations_path(version:1, wid: @workspace.unique_id)%>/{{allocationId}}">Delete</a>

      <button type="submit" class="js-submit button button--success float--right">Update</button>
    </form>
  </script>

  <script id="js-new-allocation-form-template" type="text/html">
    <div class="modal--medium">
      <h1 class="delta text--center">Allocate Resource</h1>

      <form class="js-new-allocation-form clearfix" action="<%= allocations_path(version:1, wid: @workspace.unique_id)%>" data-method="post" >
        <input class="js-resource-id" type="hidden" name="allocation[resource_id]" data-name="resource_id" value="{{resourceId}}">

        <div class="form">
          <div class="push--bottom">
            <label for="allocation[resource_group_id]" class="label"><%= @workspace.resource_groups_name %></label>

            <select class="form-control js-resource-group-id" name="allocation[resource_group_id]" data-name="resource_group_id">
              {{#resourceGroups}}
                <option value="{{id}}">{{name}}</option>
              {{/resourceGroups}}
            </select>
          </div>
        </div>

        <div class="js-availability-list">Loading availability information</div>

        <p>Or select manually:</p>

        <div class="form-inline push--bottom">
          <label for="allocation[start_date]" class="label">From</label>
          <input class="js-start-date form-control" type="text" name="allocation[start_date]" data-name="start_date" value="{{startDate}}">
          <label for="allocation[end_date]" class="label">To</label>
          <input class="js-end-date form-control" type="text" name="allocation[ent_date]" data-name="end_date" value="{{endDate}}">
        </div>

        <button type="submit" class="js-submit button button--success float--right">Allocate</button>
      </form>
    </div>
  </script>

  <script id="js-resources-list-item-template" type="text/html">
    <li><span>{{ name }}
      <a href="javascript:;" class="js-open-allocate-form button button--small button--success float--right" data-resource-name="{{ name }}" data-resource-id="{{id}}">Allocate</a> </span></li>
  </script>

  <script id="js-resources-group-template" type="text/html">
    <div class="workspace-chart__group js-workspace-chart-group" style="background-color: {{ bg_color }}">
      <div class="workspace-chart-group__title js-group-title">{{ name }}</div>
    </div>
  </script>

  <script id="js-resource-template" type="text/html">
    <div class="workspace-chart__resource js-workspace-chart-resource" data-allocation-id="{{allocationId}}">{{ name }}</div>
  </script>

  <script type="text/javascript" charset="utf-8">
    $(function () {Resorcery.init()});
    Resorcery.workspaceId = <%= @workspace.unique_id.to_json.html_safe %>;
    Resorcery.defaultDates = <%= default_dates.to_json.html_safe %>;
    NewResourceGroupForm.init(".js-new-resource-group-form");
    NewResourceForm.init(".js-new-resource-form", ".js-resources-list");
  </script>
<% end %>