config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/demo', to: "guests#show", as: "demo"

  resource :dashboard, only: [:show]

  get '/w/new', to: 'workspaces#new', as: :new_workspace
  get '/w/:wid(/:name)', to: 'workspaces#show', constraints: { wid: /[^\/]+/}, as: :workspace

  api version: 1, module: "api/v1" do
    resources :workspaces, :only => [:create, :index]

    scope '/w/:wid', constraints: { wid: /[^\/]+/} do
      resource :workspace, only: [:show], path: ""
      resources :availabilities, :only => [:show]
      resources :resources, :only => [:create]
      resources :resource_groups, :only => [:create]
      resources :allocations, :only => [:create, :index, :destroy] do
        collection do
          post '/:allocation_id', to: "allocations#update", as: :update
        end
      end
    end
  end

  root to: "pages#index"

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/views/pages/landing/_header.html.slim
header.main-header.landing__header.cf
  .container
    .main-logo
      = link_to "", root_path
    nav.nav.float--right
      = link_to new_user_registration_path, class: "button button-border--white"
        | Sign Up for Free

app/views/pages/landing/_main_banner.html.slim
.container
  .big-soft--ends
    h2.main-banner__heading.cd-headline.slide
      .cd-words-wrapper
        b.is-visible
          | Assign Teams To Projects&nbsp;
        b
          | Plan Your Soccer Team's Line Up&nbsp;
        b
          | Distribute Your Wedding's Tables&nbsp;
        b
          | Allocate Anything... Really&nbsp;
    p.main-banner__subheading
      span.weight--semibold
        | Resorcery&nbsp;
      | is a flexible multi-purpose tool to assign and visualize resource allocations

    .main-banner__buttons
      = link_to new_user_registration_path, class: "button button-border--white button--large"
        | Sign Up for Free

      span.push--sides 
        | or

      = link_to demo_path, class: "button button-border--white button--large"
        | Try the Demo

    .main-banner__links
      = link_to new_user_session_path, class: ""
        | I already have an account