config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/demo', to: "guests#show", as: "demo"

  resource :dashboard, only: [:show]

  get '/w/new', to: 'workspaces#new', as: :new_workspace
  get '/w/:wid(/:name)', to: 'workspaces#show', constraints: { wid: /[^\/]+/}, as: :workspace

  api version: 1, module: "api/v1" do
    resources :workspaces, :only => [:create, :index]

    scope '/w/:wid', constraints: { wid: /[^\/]+/} do
      resource :workspace, only: [:show], path: ""
      resources :availabilities, :only => [:show]
      resources :resources, :only => [:create]
      resources :resource_groups, :only => [:create]
      resources :allocations, :only => [:create, :index, :destroy] do
        collection do
          post '/:allocation_id', to: "allocations#update", as: :update
        end
      end
    end
  end

  root to: "pages#index"

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ResorceryController

  def show
    @workspaces = current_user.workspaces
  end
end

app/views/dashboards/show.html.erb
<div class="container container--wide">
  <div class="grid">
    <div class="grid__item one-half">
      <h1>Workspaces</h1>
    </div>
  </div>

  <div class="workspace-list grid">
    <div class="grid__item one-whole medium--one-quarter large--one-fifth js-new-workspace-container">
      <div class="workspace-list__item panel panel--small-space panel--alt">
        <span class="panel__head">
          Add New Workspace
        </span>
        <span class="panel__body">

          <form class="js-new-workspace-form" action="<%= workspaces_path(version:1)%>" data-method="post" >
            <div class="form-inline">
              <input type="text" autocomplete="off" class="form-control form-control--clear js-group-input-name js-name" placeholder="Workspace name" name="workspace[name]" data-name="name">
              <input type="submit" class="button button--info float--right js-submit" value="OK">
            </div>
          </form>

        </span>
      </div>
    </div><!--
    --><% @workspaces.each do |workspace| %><div class="grid__item one-whole medium--one-quarter large--one-fifth">
        <%= link_to workspace_path(wid: workspace.unique_id, name: workspace.name.parameterize), class: "workspace-list__item panel panel--alt panel--small-space" do %>
          <span class="panel__head" style="background-color: #<%= workspace.metadata['background_color'] %>">
            <%= workspace.name %>
          </span>
          <span class="panel__body">
            <span class="workspace-stats">
              <span class="workspace-stats__label">Groups</span>
              <span class="workspace-stats__metric">
                <%= workspace.resource_groups_count %>
              </span>
            </span>
            <span class="workspace-stats">
              <span class="workspace-stats__label">Resources</span>
              <span class="workspace-stats__metric">
                <%= workspace.resources_count %>
              </span>
            </span>
          </span>
        <% end -%>
      </div><% end -%>
  </div>
</div>

<% content_for :javascripts do %>
  <script id="js-workspace-template" type="text/html">

    <div class="grid__item one-whole medium--one-quarter large--one-fifth">
      <a class="workspace-list__item panel panel--alt panel--small-space" href="{{location}}">
        <span class="panel__head" style="background-color: #{{background_color}}">
          {{name}}
        </span>
        <span class="panel__body">
          <span class="workspace-stats">
            <span class="workspace-stats__label">Groups</span>
            <span class="workspace-stats__metric">
              {{resource_groups_count}}
            </span>
          </span>
          <span class="workspace-stats">
            <span class="workspace-stats__label">Resources</span>
            <span class="workspace-stats__metric">
              {{resources_count}}
            </span>
          </span>
        </span>
      </a>
    </div>
  </script>

  <script type="text/javascript" charset="utf-8">
    NewWorkspaceForm.init(".js-new-workspace-form");
  </script>
<% end %>